version: '3.8'

services:
  gourmet_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Monta o diretório atual para persistência de dados do SQLite
    environment:
      FLASK_ENV: development
